repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)

  - repo: local
    hooks:
    -   id: flake8
        name: wemake-python-styleguide
        description: Check code style with wemake-python-styleguide
        entry: flake8
        language: python
        types: [python]
